# Generated by Django 5.2.8 on 2025-11-11 01:00

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clans',
            fields=[
                ('tag', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('badgeId', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=3)),
                ('donationsPerWeek', models.PositiveIntegerField()),
                ('members', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('tag', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10)),
                ('lastSeen', models.DateTimeField()),
                ('expLevel', models.PositiveIntegerField()),
                ('trophies', models.PositiveIntegerField()),
                ('clanRank', models.PositiveIntegerField()),
                ('donations', models.PositiveIntegerField()),
                ('donationsReceived', models.PositiveIntegerField()),
                ('elo', models.PositiveIntegerField(default=1000)),
                ('weeklyelo', models.PositiveIntegerField(default=1000)),
                ('clanTag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clanTag', to='clashstats.clans')),
            ],
        ),
        migrations.CreateModel(
            name='BattleLogs',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('battleTime', models.DateTimeField()),
                ('gameMode', models.CharField(max_length=25)),
                ('elocalculated', models.BooleanField(default=False)),
                ('weeklyelocalculated', models.DateTimeField(default=datetime.datetime(2025, 11, 11, 1, 0, 34, 727899, tzinfo=datetime.timezone.utc))),
                ('loser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser12member', to='clashstats.members')),
                ('loser2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser22member', to='clashstats.members')),
                ('winner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner12member', to='clashstats.members')),
                ('winner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner22member', to='clashstats.members')),
            ],
        ),
        migrations.CreateModel(
            name='Refresh',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('13baa9c6-6c5e-430e-83cf-806338a9a564'), primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 11, 11, 1, 0, 34, 728115, tzinfo=datetime.timezone.utc))),
                ('source', models.CharField(default='api')),
                ('clanTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh2clan', to='clashstats.clans')),
            ],
        ),
    ]
