# Generated by Django 5.2.8 on 2025-11-07 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clans',
            fields=[
                ('tag', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('badgeId', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=3)),
                ('donationsPerWeek', models.PositiveIntegerField()),
                ('members', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('tag', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10)),
                ('lastSeen', models.DateTimeField()),
                ('expLevel', models.PositiveIntegerField()),
                ('trophies', models.PositiveIntegerField()),
                ('clanRank', models.PositiveIntegerField()),
                ('donations', models.PositiveIntegerField()),
                ('donationsReceived', models.PositiveIntegerField()),
                ('clanTag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clanTag', to='clashstats.clans')),
            ],
        ),
    ]
