# Generated by Django 6.0 on 2026-03-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clashstats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklyelo",
            name="week",
            field=models.DateField(),
        ),
    ]
