# Generated by Django 5.2.8 on 2025-11-07 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashstats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='elo',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='BattleLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('battleTime', models.DateTimeField()),
                ('gameMode', models.CharField(max_length=25)),
                ('winner1ElixirLeaked', models.PositiveIntegerField()),
                ('winner2ElixirLeaked', models.PositiveIntegerField()),
                ('loser1ElixirLeaked', models.PositiveIntegerField()),
                ('loser2ElixirLeaked', models.PositiveIntegerField()),
                ('loser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser12member', to='clashstats.members')),
                ('loser2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser22member', to='clashstats.members')),
                ('winner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner12member', to='clashstats.members')),
                ('winner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner22member', to='clashstats.members')),
            ],
        ),
    ]
