# Generated by Django 5.2.8 on 2025-11-11 01:00

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlelogs',
            name='weeklyelocalculated',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 1, 0, 40, 75931, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refresh',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c68e691-b640-44a7-b722-6488d3d98b8a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refresh',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 1, 0, 40, 76142, tzinfo=datetime.timezone.utc)),
        ),
    ]
