# Generated by Django 5.2.8 on 2025-11-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clashstats', '0002_members_elo_battlelogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlelogs',
            name='loser1ElixirLeaked',
        ),
        migrations.RemoveField(
            model_name='battlelogs',
            name='loser2ElixirLeaked',
        ),
        migrations.RemoveField(
            model_name='battlelogs',
            name='winner1ElixirLeaked',
        ),
        migrations.RemoveField(
            model_name='battlelogs',
            name='winner2ElixirLeaked',
        ),
    ]
