# Generated by Django 5.2.8 on 2025-11-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashstats', '0003_remove_battlelogs_loser1elixirleaked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlelogs',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
