# Generated by Django 5.2.8 on 2025-11-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashstats', '0004_alter_battlelogs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='elo',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
