# Generated by Django 5.2.8 on 2025-11-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashstats', '0005_alter_members_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlelogs',
            name='elocalculated',
            field=models.BooleanField(default=False),
        ),
    ]
