# Generated by Django 5.0.4 on 2024-04-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clanranking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="eloRating",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
