# Generated by Django 5.1.1 on 2024-11-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clanranking', '0002_battles_loser1name_battles_winner1namen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battles',
            old_name='winner1Namen',
            new_name='winner1Name',
        ),
    ]
