# Generated by Django 5.0.4 on 2024-04-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clanranking", "0002_members_elorating"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastUpdated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
