# Generated by Django 5.0.4 on 2024-04-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clanranking", "0004_rename_count_lastupdated_battlecount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LastUpdated",
        ),
    ]
