# Generated by Django 5.0.4 on 2024-04-18 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clanranking", "0005_delete_lastupdated"),
    ]

    operations = [
        migrations.AddField(
            model_name="clans",
            name="lastUpdated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
