# Generated by Django 5.0.4 on 2024-04-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clanranking", "0006_clans_lastupdated"),
    ]

    operations = [
        migrations.CreateModel(
            name="weekBattles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eloRating", models.PositiveIntegerField(default=1000)),
                (
                    "tag",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekBattleTag",
                        to="clanranking.members",
                    ),
                ),
            ],
        ),
    ]
