# Generated by Django 5.0.4 on 2024-04-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clanranking", "0007_weekbattles"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="weekBattles",
            new_name="weeklyRanking",
        ),
    ]
