# Generated by Django 5.0.4 on 2024-04-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arena",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.PositiveIntegerField()),
                ("maxLevel", models.PositiveIntegerField()),
                ("rarity", models.CharField(max_length=50)),
                ("elixirCost", models.PositiveIntegerField()),
                ("iconUrlsm", models.CharField(max_length=50)),
                ("iconUrlse", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "tag",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("badgeId", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GameMode",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("crowns", models.PositiveIntegerField()),
                ("kingTowerHitPoints", models.PositiveIntegerField()),
                ("princessTower1HitPoints", models.PositiveIntegerField()),
                ("princessTower2HitPoints", models.PositiveIntegerField()),
                ("elixirLeaked", models.FloatField()),
                (
                    "card1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card1",
                        to="battlelog.card",
                    ),
                ),
                (
                    "card2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card2",
                        to="battlelog.card",
                    ),
                ),
                (
                    "card3",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card3",
                        to="battlelog.card",
                    ),
                ),
                (
                    "card4",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card4",
                        to="battlelog.card",
                    ),
                ),
                (
                    "card5",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card5",
                        to="battlelog.card",
                    ),
                ),
                (
                    "card6",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card6",
                        to="battlelog.card",
                    ),
                ),
                (
                    "card7",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card7",
                        to="battlelog.card",
                    ),
                ),
                (
                    "card8",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card8",
                        to="battlelog.card",
                    ),
                ),
                (
                    "clan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="battlelog.clan",
                    ),
                ),
                (
                    "supportCards",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supportcard",
                        to="battlelog.card",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battleTime", models.DateTimeField()),
                ("type", models.CharField(max_length=100)),
                ("isLadderTournament", models.CharField(max_length=5)),
                ("deckSelection", models.CharField(max_length=50)),
                ("isHostedMatch", models.CharField(max_length=5)),
                ("leagueNumber", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "arena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battlelog.arena",
                    ),
                ),
                (
                    "gameMode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battlelog.gamemode",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opponent",
                        to="battlelog.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_battles",
                        to="battlelog.player",
                    ),
                ),
            ],
        ),
    ]
