# Generated by Django 5.0.4 on 2024-04-05 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arena",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CardIconUrls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medium", models.URLField()),
                ("evolutionMedium", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("badgeId", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GameMode",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("level", models.PositiveIntegerField()),
                ("maxLevel", models.PositiveIntegerField()),
                ("rarity", models.CharField(max_length=50)),
                ("elixirCost", models.PositiveIntegerField()),
                (
                    "iconUrls",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battlelog.cardiconurls",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("startingTrophies", models.PositiveIntegerField()),
                ("crowns", models.PositiveIntegerField()),
                ("kingTowerHitPoints", models.PositiveIntegerField()),
                ("princessTowersHitPoints", models.JSONField(blank=True, null=True)),
                ("globalRank", models.PositiveIntegerField(blank=True, null=True)),
                ("elixirLeaked", models.FloatField()),
                (
                    "cards",
                    models.ManyToManyField(related_name="players", to="battlelog.card"),
                ),
                (
                    "clan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="battlelog.clan",
                    ),
                ),
                (
                    "supportCards",
                    models.ManyToManyField(
                        blank=True,
                        related_name="supported_players",
                        to="battlelog.card",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battleTime", models.DateTimeField()),
                ("type", models.CharField(max_length=100)),
                ("isLadderTournament", models.BooleanField()),
                ("deckSelection", models.CharField(max_length=50)),
                ("isHostedMatch", models.BooleanField()),
                ("leagueNumber", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "arena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battlelog.arena",
                    ),
                ),
                (
                    "gameMode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="battlelog.gamemode",
                    ),
                ),
                (
                    "opponent",
                    models.ManyToManyField(
                        related_name="opponent_battles", to="battlelog.player"
                    ),
                ),
                (
                    "team",
                    models.ManyToManyField(
                        related_name="team_battles", to="battlelog.player"
                    ),
                ),
            ],
        ),
    ]
