# Generated by Django 5.0.4 on 2024-04-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battlelog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="iconUrls",
        ),
        migrations.RemoveField(
            model_name="player",
            name="cards",
        ),
        migrations.RemoveField(
            model_name="player",
            name="princessTowersHitPoints",
        ),
        migrations.AddField(
            model_name="card",
            name="iconUrlse",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="iconUrlsm",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="card1",
            field=models.ManyToManyField(related_name="card1", to="battlelog.card"),
        ),
        migrations.AddField(
            model_name="player",
            name="card2",
            field=models.ManyToManyField(related_name="card2", to="battlelog.card"),
        ),
        migrations.AddField(
            model_name="player",
            name="card3",
            field=models.ManyToManyField(related_name="card3", to="battlelog.card"),
        ),
        migrations.AddField(
            model_name="player",
            name="card4",
            field=models.ManyToManyField(related_name="card4", to="battlelog.card"),
        ),
        migrations.AddField(
            model_name="player",
            name="card5",
            field=models.ManyToManyField(related_name="card5", to="battlelog.card"),
        ),
        migrations.AddField(
            model_name="player",
            name="card6",
            field=models.ManyToManyField(related_name="card6", to="battlelog.card"),
        ),
        migrations.AddField(
            model_name="player",
            name="card7",
            field=models.ManyToManyField(related_name="card7", to="battlelog.card"),
        ),
        migrations.AddField(
            model_name="player",
            name="card8",
            field=models.ManyToManyField(related_name="card8", to="battlelog.card"),
        ),
        migrations.DeleteModel(
            name="CardIconUrls",
        ),
    ]
