# Generated by Django 5.0.4 on 2024-04-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battlelog", "0002_remove_card_iconurls_remove_player_cards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="isHostedMatch",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="battle",
            name="isLadderTournament",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="player",
            name="globalRank",
            field=models.CharField(default=" ", max_length=5),
            preserve_default=False,
        ),
    ]
