# Generated by Django 5.0.4 on 2024-04-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battlelog", "0003_alter_battle_ishostedmatch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="princessTower1HitPoints",
            field=models.PositiveIntegerField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="princessTower2HitPoints",
            field=models.PositiveIntegerField(default=" "),
            preserve_default=False,
        ),
    ]
