# Generated by Django 5.1.1 on 2024-10-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlelog', '0004_alter_card_iconurlse_alter_card_iconurlsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
