# Generated by Django 5.0.4 on 2024-04-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battlelog", "0004_player_princesstower1hitpoints_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="princessTower1HitPoints",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="player",
            name="princessTower2HitPoints",
            field=models.CharField(max_length=100),
        ),
    ]
