# Generated by Django 5.1.1 on 2024-10-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlelog', '0005_alter_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshTime', models.PositiveIntegerField()),
                ('smtpHost', models.CharField(max_length=100)),
                ('smtpPort', models.PositiveIntegerField()),
                ('smtpUser', models.CharField(max_length=100)),
                ('smtpPass', models.CharField(max_length=100)),
                ('smtpSender', models.CharField(max_length=100)),
            ],
        ),
    ]
