# Generated by Django 5.0.4 on 2024-04-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battlelog", "0007_alter_player_princesstower1hitpoints_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="princessTower1HitPoints",
        ),
        migrations.RemoveField(
            model_name="player",
            name="princessTower2HitPoints",
        ),
        migrations.AddField(
            model_name="player",
            name="princessTowerHitPoints1",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="princessTowerHitPoints2",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
