# Generated by Django 5.0.4 on 2024-04-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battlelog", "0008_remove_player_princesstower1hitpoints_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="princessTowerHitPoints1",
            new_name="princessTower1HitPoints",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="princessTowerHitPoints2",
            new_name="princessTower2HitPoints",
        ),
    ]
