name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make migrations
        run: |
          cd clashstats
          python manage.py makemigrations

      - name: Run migrations
        run: |
          cd clashstats
          python manage.py migrate

      - name: Run tests
        run: |
          cd clashstats
          python manage.py test

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: |
          cd clashstats
          black .
          

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -u
          git commit -m "Format Python code with Black" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
