name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures you fetch all history for .git files
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensures the checkout action has permission to check out the code

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make migrations
        run: |
          cd clashstats
          python manage.py makemigrations

      - name: Run migrations
        run: |
          cd clashstats
          python manage.py migrate

      - name: Run tests
        run: |
          cd clashstats
          python manage.py test

      - name: Install Black
        run: pip install black

      - name: Run Black and check for changes
        run: |
          cd clashstats
          black . --check --diff

      - name: Commit changes if any
        if: ${{ steps.black.outputs.has-changes == 'true' }}
        run: |
          git add -A
          git commit -m "Format Python code with Black"
          git push origin HEAD:${{ github.ref }}
